# Generated by Django 5.1.7 on 2025-03-26 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas_online', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportista', models.CharField(max_length=100)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('preparando', 'Preparando'), ('en_transito', 'En Tránsito'), ('entregado', 'Entregado')], max_length=20)),
                ('numero_seguimiento', models.CharField(blank=True, max_length=50)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventas_online.pedido')),
            ],
        ),
    ]
